title: Download & installing Canon Printer Driver |  Canon Wireless Printer Setup
description: Visit Canon.com/ijsetup and download the driver software for your device. Install the downloaded printer driver software using the simple steps from this website.
